export type KeyboardDirectionalNavigationKey
  = | 'Backspace'
    | 'Delete'
    | 'Tab'
    | 'Escape'
    | 'ArrowLeft'
    | 'ArrowRight'
    | 'ArrowUp'
    | 'ArrowDown'
    | 'Home'
    | 'End'
